authorName: NNI Example
experimentName: tf2-nn TF v2.x
trialConcurrency: 1
maxExecDuration: 110h # max executable time
maxTrialNum: 500 # max trial num
trainingServicePlatform: local
searchSpacePath: search_space.json # path of search space
useAnnotation: false
tuner:
    builtinTunerName: TPE
    classArgs:
        optimize_mode: maximize # choices: maximize, minimize
    gpuIndices: "1" # specify GPUof optimizer
trial:
    command: python3 train.py GGNN GraphBinaryClassification ../data/data/ssrf --patience 100 # execute commands
    codeDir: .
    gpuNum: 0
logDir: /home/nisl1/nisl8121/hh/nni # log
localConfig:
    gpuIndices: "0" # specify GPU number
    useActiveGpu: true
