authorName: NNI Example
experimentName: CWE-77
trialConcurrency: 1
maxExecDuration: 3h # max executable time :110h
maxTrialNum: 30 # max trial num:500
trainingServicePlatform: local
searchSpacePath: search_space.json # path of search space
useAnnotation: false
tuner:
    builtinTunerName: TPE
    classArgs:
        optimize_mode: maximize # choices: maximize, minimize
    gpuIndices: "1" # specify GPUof optimizer
trial:
    command: python train.py GGNN GraphBinaryClassification ../data/data/CWE-77 # execute commands
    codeDir: .
    gpuNum: 0
logDir: /home/nisl1/nisl8121/xrz/FUNDED_NISL/FUNDED/cli/log # log
localConfig:
    gpuIndices: "0" # specify GPU number
    useActiveGpu: true
assessor:
    builtinAssessorName: Medianstop
    classArgs:
        optimize_mode: maximize
        start_step: 20
